#!/usr/bin/env bash
# Chapter 2 substrate — a NAT'd guest VM for lesson 5 (OpenShell).
#
# WHY THIS EXISTS, because it looks like gratuitous nesting until you hit the wall:
#
# OpenShell's rootless-podman driver reads the HOST's default-route interface and refuses to start
# if its address is public:
#
#     compute driver 'podman' requested the gateway default-route interface, but its resolved
#     address <public ip> is not a private IPv4 address
#
# That is a safety check, not a bug — it will not expose the sandbox->gateway callback on a public
# address. And every Scaleway box has a public default route: Elastic Metal by definition, and an
# Instance too (measured 2026-08-05: routed-IP puts the public /32 directly on ens2). Faking it by
# rewriting the route's `src` gets the gateway to START and then fails at the callback bind, because
# pasta maps `host.containers.internal` to its own fixed alias. See substrates/README.md.
#
# What OpenShell actually needs is a NAT topology — a genuine private PRIMARY address on the
# default-route interface. libvirt's `default` network is exactly that (virbr0, 192.168.122.0/24,
# masqueraded), so this builds one guest on it and lesson 5 runs INSIDE the guest. That is the same
# shape that makes OpenShell work on a laptop, where the private address is the home LAN's.
#
# Debian 13 on purpose: podman 5 + pasta-by-default is the other hard requirement, and Ubuntu 24.04
# still ships podman 4.9.3, which fails it.
set -euo pipefail

GUEST=openshell-guest
IMG_URL="https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2"
POOL=/var/lib/libvirt/images
SEED="${POOL}/${GUEST}-seed.iso"
DISK="${POOL}/${GUEST}.qcow2"
# The guest has to trust TWO keys, and missing either one is a confusing failure:
#   * the key the workstation reached this box with, so `up.sh` can ProxyJump straight through;
#   * a key belonging to root ON THIS BOX, because this script runs under sudo and needs its own
#     way in to wait for cloud-init. Root has no private key by default, so we mint one — reusing
#     the workstation's would mean copying a private key onto a box running hostile code.
HOST_AUTHKEYS="${SUDO_USER:+/home/${SUDO_USER}}/.ssh/authorized_keys"
[ -f "${HOST_AUTHKEYS}" ] || HOST_AUTHKEYS=/root/.ssh/authorized_keys
BOX_KEY=/root/.ssh/id_ed25519
[ -f "${BOX_KEY}" ] || ssh-keygen -t ed25519 -N "" -C "sandboxing-tutorial box->guest" -f "${BOX_KEY}" >/dev/null

test -e /dev/kvm || {
  echo "FATAL: /dev/kvm absent — this substrate needs hardware virtualisation."
  exit 1
}

export DEBIAN_FRONTEND=noninteractive
apt-get -qq update
# ovmf is not optional — see the --boot uefi note below.
apt-get -qq install -y qemu-system-x86 libvirt-daemon-system libvirt-clients virtinst \
  cloud-image-utils genisoimage qemu-utils ovmf >/dev/null
systemctl enable --now libvirtd >/dev/null 2>&1 || true
virsh net-start default >/dev/null 2>&1 || true
virsh net-autostart default >/dev/null 2>&1 || true

if virsh domstate "${GUEST}" >/dev/null 2>&1; then
  echo "${GUEST} already exists: $(virsh domstate "${GUEST}")"
else
  [ -f "${POOL}/debian13-base.qcow2" ] || curl -fsSL "${IMG_URL}" -o "${POOL}/debian13-base.qcow2"
  qemu-img create -f qcow2 -F qcow2 -b "${POOL}/debian13-base.qcow2" "${DISK}" 20G >/dev/null

  # cloud-init: one unprivileged user (OpenShell's podman driver is ROOTLESS — running the gateway
  # as root clears the private-IP check but then fails to bind the callback to the bridge IP), the
  # host's own key, podman 5 + passt, and a lingering user session so the rootless podman socket
  # survives without an interactive login.
  #
  # Three things below are load-bearing and each was measured failing (2026-08-06):
  #
  #  * `packages:` sits at COLUMN 0. Indented by two spaces it is invalid YAML at the document's
  #    top level, and cloud-init then discards the WHOLE user-data as "empty cloud config" — no
  #    agent user, no podman, no hostname. The guest boots and takes a lease, so the only symptom
  #    is `Permission denied (publickey)` on the next hop, which reads like a key problem.
  #  * the authorized_keys line is FILTERED to real key lines. On a Scaleway VM that file is
  #    generated by scw-fetch-ssh-keys with a 16-line comment header, and prefixing every line with
  #    "- " feeds cloud-init `- #` list items. On Elastic Metal the file is plain keys, which is
  #    why this only appears on VMs.
  #  * there is no `systemctl --machine=agent@.host` runcmd. `--machine` needs systemd-container,
  #    which a cloud image does not ship, so the runcmd fails and takes cloud-init's final stage
  #    with it (`cloud-init status` -> error). 40-openshell.sh enables the socket as the user.
  #
  # This heredoc is UNQUOTED because it interpolates the keys — so nothing inside it, comments
  # included, may contain $(...) unless you actually want it run on this box.
  cat >/tmp/user-data <<EOF
#cloud-config
hostname: ${GUEST}
users:
  - name: agent
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true
    ssh_authorized_keys:
$(grep -E '^(ssh-|ecdsa-|sk-ssh-|sk-ecdsa-)' "${HOST_AUTHKEYS}" | sed 's/^/      - /')
      - $(cat "${BOX_KEY}.pub")
package_update: true
# podman-docker provides /usr/bin/docker -> podman. 'openshell doctor check' shells out to a
#   docker-compatible CLI, so without it the doctor fails even though the driver is fine.
packages: [podman, podman-docker, passt, uidmap, slirp4netns, fuse-overlayfs, curl, ca-certificates, jq, rsync, python3]
runcmd:
  - [ loginctl, enable-linger, agent ]
EOF
  echo "instance-id: ${GUEST}; local-hostname: ${GUEST}" >/tmp/meta-data
  cloud-localds "${SEED}" /tmp/user-data /tmp/meta-data

  # --boot uefi is LOAD-BEARING. Debian 13's genericcloud image is UEFI-only; booted on the default
  # BIOS firmware it gets as far as grub, prints its "Booting Debian GNU/Linux" line, and the kernel
  # then resets in a loop forever. Nothing reaches the serial console, because grub hands off before the
  # kernel would configure one — so the symptom is a guest that never takes a DHCP lease and gives no
  # reason. Measured on bare metal and on a nested host alike, which is what ruled out virtualisation
  # as the cause.
  # --serial file keeps the guest's console where a human can read it if this ever regresses.
  virt-install --name "${GUEST}" --memory 3072 --vcpus 2 --import --boot uefi \
    --disk "path=${DISK},format=qcow2" --disk "path=${SEED},device=cdrom" \
    --os-variant debian12 --network network=default --graphics none \
    --serial "file,path=/var/log/${GUEST}-console.log" --noautoconsole >/dev/null
  virsh autostart "${GUEST}" >/dev/null 2>&1 || true
fi

# The guest's DHCP lease is the whole output of this script: it is the PRIVATE address that makes
# OpenShell's check pass, and up.sh re-points the lesson's box at it.
echo -n "waiting for ${GUEST} to take a lease"
for _ in $(seq 1 60); do
  IP=$(virsh domifaddr "${GUEST}" 2>/dev/null | awk '/ipv4/ {split($4, a, "/"); print a[1]; exit}')
  [ -n "${IP:-}" ] && break
  echo -n "."
  sleep 5
done
echo
[ -n "${IP:-}" ] || {
  echo "FATAL: ${GUEST} never took a DHCP lease on virbr0"
  exit 1
}

# Wait for cloud-init to finish, or the first ssh lands before podman exists.
for _ in $(seq 1 60); do
  ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR \
    -o ConnectTimeout=5 -i "${BOX_KEY}" "agent@${IP}" 'cloud-init status --wait >/dev/null 2>&1 || true; command -v podman' >/dev/null 2>&1 && break
  sleep 10
done

echo "GUEST_IP=${IP}" >/etc/sandboxing-tutorial-guest.env
echo "${GUEST}: ${IP}  (private, NAT'd via virbr0 — this is what OpenShell needs)"
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i "${BOX_KEY}" "agent@${IP}" \
  'echo "  guest podman : $(podman --version)"; echo "  guest default route: $(ip route show default)"'
